Feature  user account creation
bnaylor1989/NewBank pull request #1
Opened 2021-07-07 17:15 UTC by AllenNinous

2021-07-08 22:24 UTC, bnaylor1989 requested changes
This is really good. After you have addressed these comments, particularly the print issues in withdrawAmount method in the NewBank class, I would like to review again quickly before merging. Thanks

2021-07-08 22:24 UTC, bnaylor1989 commented on src/server/InputProcessor.java
> +                // Upon matching, break and return the given input
Please update this comment.

2021-07-08 22:24 UTC, bnaylor1989 commented on src/server/NewBank.java
> +		String accountName = InputProcessor.takeValidInput(customers.get(customer.getKey()).getAccounts());
This code is fairly hard to read in my opinion. As customers.get(customer.getKey()).getAccounts() is repeated often, can this be stored in a variable as shown below. This could reduce a lot of repetition and increase readibility.

ArrayList customerAccounts = customers.get(customer.getKey()).getAccounts();

2021-07-08 22:24 UTC, bnaylor1989 commented on src/server/InputProcessor.java
> +    public static void main(String[] args) {
As you have said. Can this method be removed before merging.

2021-07-08 22:24 UTC, bnaylor1989 commented on src/server/InputProcessor.java
> +    // public static String takeValidInput(String key, String oldPass)
Does this comment need removing now?

2021-07-09 07:18 UTC, AllenNinous commented on src/server/InputProcessor.java
> +                    continue;
Done

2021-07-09 07:22 UTC, AllenNinous commented on src/server/InputProcessor.java
> +                // Upon matching, break and return the given input
Done

2021-07-09 07:22 UTC, AllenNinous commented on src/server/InputProcessor.java
> +        }
Done.

2021-07-09 07:23 UTC, AllenNinous commented on src/server/InputProcessor.java
> +                    continue;
Good point. Done.

2021-07-09 07:25 UTC, AllenNinous commented on src/server/InputProcessor.java
> +                continue;
Done.

2021-07-09 07:32 UTC, AllenNinous commented on src/server/InputProcessor.java
> +    // public static String takeValidInput(String key, String oldPass)
I would suggest keeping it in case anyone decided to follow the same input validation process. I included the method signature as some sort of guidance.

2021-07-09 07:37 UTC, AllenNinous commented on src/server/InputProcessor.java
> +    public static void main(String[] args) {
I'm used to keeping it for running small tests until finally delivering the project in full but if you think it's better practice to remove it before making this merge then no problem. Removed.

2021-07-09 07:54 UTC, AllenNinous commented on src/server/NewBank.java
> +		System.out.println(showMyAccounts(customer));
The PrintWriter object in NewBankClientHandler.java has a separate OutputStream. Therefore, all System.outs will be shown on the console where the server was initiated. There is a workaround but it might cause tight coupling so I thought waiting for the team to decide on how to approach this was better than over-modifying other classes. You can still see the output on your first console.

2021-07-09 08:10 UTC, AllenNinous commented on src/server/NewBank.java
> +		String accountName = InputProcessor.takeValidInput(customers.get(customer.getKey()).getAccounts());
Done.

2021-07-09 08:11 UTC, AllenNinous commented on src/server/InputProcessor.java
> +        }
Done.

2021-07-09 20:20 UTC, bnaylor1989 requested changes
Just a few minor requests. There are some comments that relate to making the user input case insensitive. I may have missed a few but please could all user input be case insensitive.

2021-07-09 20:20 UTC, bnaylor1989 commented on src/server/NewBankClientHandler.java
> +								System.out.println("Request from " + customer.getKey());
Just need to get rid of 'System'
out.println("Request from " + customer.getKey());

2021-07-09 20:20 UTC, bnaylor1989 commented on src/server/NewBankClientHandler.java
> +								String request = in.readLine();
After going through the loop once, for example making a successful withdrawal, when you get back to this point there is no prompt to the user to do anything. I think it would make sense tosplit the output like below:

if (customer != null) {
	out.println("Log In Successful.");
	while (true) {
                out.println("What do you want to do?");
		String request = in.readLine();

2021-07-09 20:20 UTC, bnaylor1989 commented on src/server/NewBankClientHandler.java
> +								if (request.equals("MENU")) {
I think this should not be case sensitive, if you agree could you change to .equalsIgnoreCase("MENU")

2021-07-09 20:20 UTC, bnaylor1989 commented on src/server/NewBank.java
>  			case "SHOWMYACCOUNTS" : return showMyAccounts(customer);
It would be nice for this to not have to be uppercase. You could leave the cases in the switch statement the same but change the following:
switch(request.toUpperCase())
It just enhances the user experience that little bit.

2021-07-09 20:42 UTC, AllenNinous commented on src/server/NewBankClientHandler.java
> +								System.out.println("Request from " + customer.getKey());
That System.out.println() statement is already in the skeleton code and it's supposed to log user activity so I left it there.

2021-07-09 20:48 UTC, AllenNinous commented on src/server/NewBank.java
>  			case "SHOWMYACCOUNTS" : return showMyAccounts(customer);
Will do.

2021-07-09 20:49 UTC, AllenNinous commented on src/server/NewBankClientHandler.java
> +								if (request.equals("MENU")) {
Agreed. Will do.

2021-07-10 13:15 UTC, AllenNinous commented on src/server/NewBank.java
>  			case "SHOWMYACCOUNTS" : return showMyAccounts(customer);
Done

2021-07-10 13:15 UTC, AllenNinous commented on src/server/NewBankClientHandler.java
> +								if (request.equals("MENU")) {
Done

2021-07-10 13:43 UTC, AllenNinous commented on src/server/NewBankClientHandler.java
> +								String request = in.readLine();
Done.

2021-07-10 15:03 UTC, AllenNinous commented on src/server/NewBankClientHandler.java
> +								if (request.equals("MENU")) {
Documenting this here following our agreement of Slack:
The post-login menu will now prompt the user to input a number that represents the command instead of typing it all out.

2021-07-10 15:03 UTC, AllenNinous commented on src/server/NewBank.java
>  			case "SHOWMYACCOUNTS" : return showMyAccounts(customer);
Documenting this here following our agreement of Slack:
The post-login menu will now prompt the user to input a number that represents the command instead of typing it all out.

2021-07-10 19:00 UTC, bnaylor1989 approved these changes
Great stuff Allen. Thanks for addressing all the comments I had. Happy for you to merge this now.

2021-07-11 06:25 UTC, merged