Feature/loans
bnaylor1989/NewBank pull request #11
Opened 2021-07-25 11:43 UTC by AllenNinous

2021-07-26 00:42 UTC, Ecenursahin reviewed
Allen, this is a very comprehensive work for the loan system, thank you for the amazing work. Especially the table looks very neat when reviewing the accounts. When we add a loan to an account shall we show the loan amount in a separate line or column? As of now when the loan is approved it shows the aggreagate amount. For a user to see the initial loan amount separately would it be helpful?
Also it is great that you integrated interest feature. When paying pack the loan it adds that too. 
Overall this is an amazing work! Thank you for all your valuable effort! :)

2021-07-26 00:42 UTC, Ecenursahin commented on src/main/java/server/NewBankClientHandler.java
> +
Great addition to take care of Admin account processes, later we might change the numbers to operation names but for now for the sake of simplicity in design and testing this looks great!

2021-07-26 00:42 UTC, Ecenursahin commented on src/main/java/server/OutputProcessor.java
> +
This also makes the overall loan table display much nicer, great design Allen! Thank you for all the amazing work!

2021-07-26 05:32 UTC, kezuk23 commented on src/main/java/server/NewBank.java
> +			return String.format("There is no account found under this customer.");
Just a minor change to either "There is no account found for this customer" // "There is no account found under this customer name"

2021-07-26 05:33 UTC, kezuk23 commented on src/main/java/server/NewBank.java
> +					+ "(choose from the list below):" + "\nPlease enter Exit to go back to the main menu.");
"Please enter Exit to go back..." might sound better as "Type EXIT to return to main menu" for clarity

2021-07-26 05:34 UTC, kezuk23 commented on src/main/java/server/NewBank.java
> +			if(accountNumber.equals("Exit")){
If you change Exit to EXIT, don't forget this part

2021-07-26 05:36 UTC, kezuk23 commented on src/main/java/server/NewBank.java
> +				if (accountNumber.equalsIgnoreCase("EXIT")) {
There is some confusion with the input cases, I'm going to add a card for tidying up so that it's all consistent throughout. Hopefully that'll be easier for the user.

2021-07-26 05:43 UTC, kezuk23 commented on src/main/java/server/OutputProcessor.java
> +
Agreed!!

2021-07-26 05:47 UTC, kezuk23 reviewed
This all looks great Allen, nice work. You've clearly gone to a lot of effort with these changes and it shows. 

Because there are so many changes, it might be a good idea for our experienced teammates @bnaylor1989 or @m-c-hill to take a look and see if they can spot anything we might have missed. I'm otherwise happy to approve as Scrum Master for this week. 

I echo Ece's overall comments and have resolved them so that it's ready to approve shortly.

2021-07-26 07:50 UTC, AllenNinous commented on src/main/java/server/NewBank.java
> +			return String.format("There is no account found under this customer.");
Done.

2021-07-26 07:51 UTC, AllenNinous commented on src/main/java/server/NewBank.java
> +					+ "(choose from the list below):" + "\nPlease enter Exit to go back to the main menu.");
Done

2021-07-26 07:51 UTC, AllenNinous commented on src/main/java/server/NewBank.java
> +			if(accountNumber.equals("Exit")){
Done

2021-07-26 07:51 UTC, AllenNinous commented on src/main/java/server/NewBank.java
> +
Thank you!

2021-07-26 07:54 UTC, AllenNinous commented on src/main/java/server/NewBankClientHandler.java
> +
Agreed. Thank you

2021-07-26 07:54 UTC, AllenNinous commented on src/main/java/server/OutputProcessor.java
> +
Thank you!

2021-07-26 07:55 UTC, AllenNinous commented on src/main/java/server/User.java
Thank you

2021-07-26 07:56 UTC, AllenNinous commented on src/main/java/server/InputProcessor.java
Thank you

2021-07-26 07:56 UTC, AllenNinous commented on src/main/java/server/InputProcessor.java
> +
Thank you

2021-07-26 21:55 UTC, bnaylor1989 requested changes
Wow this is a hell of a lot of work! I really enjoyed reviewing this. Great job! Just a few comments to address.

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/Admin.java
> +    private BankLoan selectLoanRequest(String customerName, ArrayList<BankLoan> loansList){
Does this method assume that a customer can only have one pending loan request?

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/Admin.java
> +                    out.println("Process completed successfully.");
Should these console messages say something about whether the process was an acceptance or a rejection?

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/Admin.java
> +                    out.println("Process completed successfully.");
Same as comment above

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/Admin.java
> +
remove blank line please

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/NewBank.java
> +					return admins.get(admin).showLoansList(this.loansList, out);
Do you need 'this' in front of .loansList? You haven't used it in the second case statement? Could you make them consistent please.

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/Admin.java
> +        bankLoan.getCustomer().setAllowedToRequestLoan(true);
do you need to setAccepted(false) here?

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/Admin.java
> +        if (this.role.isAllowedToViewLoanRequests()) {
use checkPermission() method?

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/BankLoan.java
> +    private Account account;
Is this the account that will recieve the loan? If so could you make the name a bit more descriptive? Maybe recipientAccount?

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/Customer.java
> +	public Customer(int userID, String prefix, String fName, String lName, String nationalInsuranceNumber,
Just looking at your comments. Does this need removing before merging?

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/InputProcessor.java
> +    public static String takeValidInput(ArrayList<Account> accountsList, double amountToPayBack, BufferedReader in, PrintWriter out){
This may be just a matter of personal taste but I feel like this method could have its own name, rather than reusing th overloaded method name. Could it be called something like 'selectValidRepaymentAccount'?
Feel free to ignor ethis comment if you disagree.

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/Admin.java
> +                out.println("Enter the name of the customer you wish to handle a request for:");
Looking at the takeValidCustomerNameInput() method, it seems to be expectin the first name only. If that is what you want to do you should probably specify that in this prompt.

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/InputProcessor.java
> +                     if (bankLoan.getCustomer().getFirstName().equalsIgnoreCase(customerName)) {
Should the application only check first name when identifying a customer? Maybe it should use the last name as well. Or maybe we should use the customerId, once the database is fully hooked up.

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/NewBank.java
> +					"Has all the administartive privileges.",
typo in 'administartive'

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/OutputProcessor.java
> +        "+---------------+-----------------------------------+------+------+---------+---------+---------+%n" +
I love these table formats you have added.

2021-07-26 21:55 UTC, bnaylor1989 commented on src/main/java/server/User.java
> +    // Remove after testing
Looking at your comment, does this constructor need removing now?

2021-07-27 06:28 UTC, AllenNinous commented on src/main/java/server/Admin.java
> +    // Remove after testing
Yes. Will do.

2021-07-27 06:32 UTC, AllenNinous commented on src/main/java/server/Admin.java
> +        if (this.role.isAllowedToHandleLoanRequests()) {
You are absolutely right. Matt wrote the method so I thought that it was only there for us to perform checks on specific admins. Great technique actually.

2021-07-27 06:33 UTC, AllenNinous commented on src/main/java/server/Admin.java
> +                out.println("Enter the name of the customer you wish to handle a request for:");
Yes, it expects the first name only, for now of course. I made a change in the prompt to emphasize on that.

2021-07-27 06:34 UTC, AllenNinous commented on src/main/java/server/Admin.java
> +
Done

2021-07-27 06:36 UTC, AllenNinous commented on src/main/java/server/Admin.java
> +    private BankLoan selectLoanRequest(String customerName, ArrayList<BankLoan> loansList){
I've written it so that each customer is allowed one pending loan request, yes.

2021-07-27 06:37 UTC, AllenNinous commented on src/main/java/server/Admin.java
> +        if (this.role.isAllowedToViewLoanRequests()) {
Done.

2021-07-27 06:41 UTC, AllenNinous commented on src/main/java/server/BankLoan.java
> +    private Account account;
Done

2021-07-27 06:42 UTC, AllenNinous commented on src/main/java/server/Admin.java
> +                    out.println("Process completed successfully.");
Done

2021-07-27 06:43 UTC, AllenNinous commented on src/main/java/server/Admin.java
> +                    out.println("Process completed successfully.");
Done

2021-07-27 06:45 UTC, AllenNinous commented on src/main/java/server/Admin.java
> +                BankLoan bankLoan = selectLoanRequest(customerName, loansList);
Agreed, it's more efficient. Done.

2021-07-27 06:45 UTC, AllenNinous commented on src/main/java/server/Admin.java
> +        bankLoan.getCustomer().setAllowedToRequestLoan(true);
The accepted property is always initially false. Even when a loan is paid back, it will not change its status back to false as the request will only remain as an old record in the list. What are your thoughts?

2021-07-27 06:46 UTC, AllenNinous commented on src/main/java/server/NewBank.java
> +					return admins.get(admin).showLoansList(this.loansList, out);
That is true. Fixed.

2021-07-27 06:47 UTC, AllenNinous commented on src/main/java/server/NewBank.java
> +					"Has all the administartive privileges.",
Fixed.

2021-07-27 06:49 UTC, AllenNinous commented on src/main/java/server/InputProcessor.java
> +                     if (bankLoan.getCustomer().getFirstName().equalsIgnoreCase(customerName)) {
I'm using first name here as a temporary unique identifier for the customer. customerID would be the ideal identifier once the database is connected

2021-07-27 06:52 UTC, AllenNinous commented on src/main/java/server/InputProcessor.java
> +    public static String takeValidInput(ArrayList<Account> accountsList, double amountToPayBack, BufferedReader in, PrintWriter out){
I agree. My initial idea was to have multiple overloads for the same method (takeValidInput()) but as this class became bigger, naming got a bit messier. I suggest doing a major renaming of the methods in this class.

2021-07-27 06:53 UTC, AllenNinous commented on src/main/java/server/Customer.java
> +	public Customer(int userID, String prefix, String fName, String lName, String nationalInsuranceNumber,
Yes. Will do.

2021-07-27 06:55 UTC, AllenNinous commented on src/main/java/server/OutputProcessor.java
> +    private static final String loanTableContentFormat = "|%-15s|%-35s|%-6s|%-6s|%-9s|%-9s|%-9s|%n";
Totally forgot about this convention. Thanks for reminding me and it is fixed for both final props

2021-07-27 06:55 UTC, AllenNinous commented on src/main/java/server/OutputProcessor.java
> +        "+---------------+-----------------------------------+------+------+---------+---------+---------+%n" +
Thank you.

2021-07-27 15:33 UTC, bnaylor1989 commented on src/main/java/server/Admin.java
> +        bankLoan.getCustomer().setAllowedToRequestLoan(true);
Yeah that sounds good to me. I had missed that setAccepted is flase by default.

2021-07-27 15:34 UTC, bnaylor1989 commented on src/main/java/server/InputProcessor.java
> +    public static String takeValidInput(ArrayList<Account> accountsList, double amountToPayBack, BufferedReader in, PrintWriter out){
Okay cool. I guess that could be done as part of a separate task, as this branch is already quite large.

2021-07-27 19:32 UTC, bnaylor1989 approved these changes

2021-07-28 08:29 UTC, m-c-hill approved these changes

2021-07-28 08:30 UTC, merged