I have included the sms feature for the bank user operations.
bnaylor1989/NewBank pull request #14
Opened 2021-07-28 14:44 UTC by Ecenursahin

Now a user receives a text when:
1-withdraw
2-deposit
3-create account
4-apply for a loan
5-when a loan is approved or rejected
6-when they pay back a loan

2021-07-29 19:58 UTC, bnaylor1989 requested changes
Really great work Ece! Just a few comments to have a think about.

2021-07-29 19:58 UTC, bnaylor1989 commented on pom.xml
> +         <dependency>
Please can you make the indentation and spacing consistent.

2021-07-29 19:58 UTC, bnaylor1989 commented on src/main/java/server/NewBank.java
> +	/* This method allows to send an SMS using external Twilio hosting service
If you add another asterix * to this you can make this a proper javadoc. 
/**
*
*
**/

2021-07-29 19:58 UTC, bnaylor1989 commented on src/main/java/server/NewBank.java
> +	public void sendText(String notification) {
I think it would be good to have all methods reolating to SMS notifications in a separate class. You can also then move the 4 constants this method uses into the new class. Just thinking it would help to keep the size of the NewBank class reasonable. What do you think?

2021-07-29 19:58 UTC, bnaylor1989 commented on src/main/java/server/NewBank.java
> +
I really like this. Nice and simple and clean.

2021-07-29 19:58 UTC, bnaylor1989 commented on src/main/java/server/NewBank.java
> +							sendText (sms_notification);
I think it would be good to combine the sms_notification string and the string athat is returned below on line 401 into a single string that can be used for both. Like in showMyLoanStatus()
Just need to find the right wording.

2021-07-29 19:58 UTC, bnaylor1989 commented on src/main/java/server/NewBank.java
This is definitley a good practice for keeping sensitive infomation secure and out of code repositories. I'm just trying to think how we can make it easy for the lecturers to run this application when they come to mark our work. Could we provide them with some sort of script that they can just run and it will set up these environmental variables for them automatically perhaps?

2021-07-30 11:45 UTC, Ecenursahin commented on pom.xml
> +         <dependency>
Sure!

2021-07-30 11:46 UTC, Ecenursahin commented on src/main/java/server/NewBank.java
> +	/* This method allows to send an SMS using external Twilio hosting service
Thank you for the suggestion, I fix that! Great call for my future comment style!

2021-07-30 11:47 UTC, Ecenursahin commented on src/main/java/server/NewBank.java
> +
Thank you!

2021-07-30 11:48 UTC, Ecenursahin commented on src/main/java/server/NewBank.java
I will search for a way to do it easier for our lecturers.

2021-07-30 12:09 UTC, Ecenursahin commented on src/main/java/server/NewBank.java
> +	public void sendText(String notification) {
I created a new class called Sms.java

2021-07-30 12:10 UTC, Ecenursahin commented on src/main/java/server/NewBank.java
> +	public void sendText(String notification) {
I completely agree with you!

2021-07-30 12:10 UTC, Ecenursahin commented on src/main/java/server/NewBank.java
> +							sendText (sms_notification);
I made the statement into one by combining them, looks more concise and organized now. Thank you!

2021-07-30 22:23 UTC, bnaylor1989 approved these changes
Great work Ece

2021-07-31 11:44 UTC, AllenNinous approved these changes
Hey @Ecenursahin. I'm quite happy that you added this feature to our app. Not because I felt that we needed to add more things to it, but to actually learn about how SMS verification can be implemented in apps. You've also made it look very straight forward and this will definitely be added to my knowledge base. Regarding the code, it looks very clean and I like how you encapsulated the SMS functionality in a class of its own. Good call on making the class static as I believe there's potential for it to be utilized from multiple classes - not limiting its use to NewBank.java only. Great work and good job!

2021-07-31 14:13 UTC, Ecenursahin commented
Thank you Allen and Ben, I am very glad to hear your feedback that the feature looks nice and clean!

2021-07-31 17:37 UTC, merged