Password security features (encryption, login authentication and password reset requests)
bnaylor1989/NewBank pull request #16
Opened 2021-07-28 20:22 UTC by m-c-hill

2021-07-30 09:40 UTC, m-c-hill commented
This PR introduces password encryption - the user's plain text password is encrypted using a salt and hash method, which is in turn stored in the database. An authentication method compares the encryption of an entered password to the password currently stored in the database.

Other changes:
- Refactoring the NewBankClientHandler into menu functions with enhanced authentication features (isCustomer and isAdmin methods)
- GetObject class to retrieve data from the database and convert them into their respective objects
- Organising the project into relevant packages (ie. database, user, bank)
- Restructuring of the database schema and updates to the dummy data

2021-07-31 19:04 UTC, m-c-hill commented
This PR introduces password encryption - the user's plain text password is encrypted using a basic salt and hash method, and then stored in the database. It then authenticates the password by comparing the stored encryption against the encryption of the password entered by the user.
Other changes:
- Method to reset a user's password using the existing salt (will need to add this into the menu at some point)
- Updates to the login system - enhanced the authentication by introducing the methods isCustomer and isAdmin
- Creation of the class GetObject which takes data from the database and transforms it into objects that can be used in the code (so far this includes accounts and customers, but will be extended shortly).
- Restructuring of NewBankClientHandler to separate each menu into different methods (makes it a bit easier to read).
- Organising the project to place similar classes into relevant packages (ie. bank, database, user).
- Updated processAdminRequest and processCustomerRequest to now pass in admin and customer objects, respectively (rather than credentials).
- Added JUnit dependency to maven and set up the test directory so that we can start writing a few basic tests.

Note:
- This may temporarily break processAdminRequest as I haven't finished pulling admin objects and their roles from the database. Will try to get that fixed this weekend.
- The database may need updating if we're going down the route of a customer having multiple accounts rather than multiple balances? Does anyone have any thoughts on this?
- I still need to rectify adding new accounts to the database when a user requests to open a new account - this will also be a priority for the weekend
- Inevitably this will introduce some bugs - I'll try and do some more testing for this PR at the weekend also.

2021-07-31 21:38 UTC, bnaylor1989 requested changes
Really excellent work. The code base is starting to look much cleaner now. I'd be insterested to know what you thought the "obvious issues" were in this PR? I am currently unable to start the application, as it triggers a null pointer exception when trying to instantiate the test users. Sent you some info in Slack including screenshots.

2021-07-31 21:38 UTC, bnaylor1989 commented on src/main/java/server/user/Password.java
> +		storeSaltAndHash(salt, newHash);
Do you need this line? This will try to add a new record to the password table won't? You have the UPDATE statement below. That should be enough shouldn't it? Unless I am missing something here.

2021-07-31 21:38 UTC, bnaylor1989 commented on src/main/java/server/user/Registration.java
> +		String number = "";
Can this line be removed now?

2021-07-31 21:38 UTC, bnaylor1989 commented on src/main/java/server/user/Registration.java
> +	public boolean checkLoginExists(String login){
Bit of duplication here. The exact same method exists in the Password class. Maybe have this method in some sort of utils class which both the Password and Registration classes can use.

2021-07-31 21:38 UTC, bnaylor1989 commented on src/main/java/server/Main.java
> +	public static void main(String[] args) throws IOException, NoSuchAlgorithmException, InvalidKeySpecException {
Is this here just for testing purposes?

2021-08-01 07:46 UTC, m-c-hill commented on src/main/java/server/database/GetObject.java
> +		// TODO: redo address table in database
Yeah this is now done - I've removed it from the database so I'll get rid of this line.

2021-08-01 07:49 UTC, m-c-hill commented on src/main/java/server/database/GetObject.java
> +		String query = "SELECT * FROM customer c LEFT JOIN user u ON c.user_id = u.user_id LEFT JOIN account a ON a.account_number = c.account_number LEFT JOIN balance b ON a.account_number = b.account_num
Resolved

2021-08-01 07:50 UTC, m-c-hill commented on src/main/java/server/user/Password.java
> +		storeSaltAndHash(salt, newHash);
You're right - this is unnecessary.

2021-08-01 07:50 UTC, m-c-hill commented on src/main/java/server/user/Registration.java
> +		String number = "";
Done

2021-08-01 07:52 UTC, m-c-hill commented on src/main/java/server/Main.java
> +	public static void main(String[] args) throws IOException, NoSuchAlgorithmException, InvalidKeySpecException {
Yeah for now - I probably shouldn't have pushed it, but it was useful for testing some of the encryption methods on their own.

I'll delete it from git and just keep it locally for now.

2021-08-01 07:52 UTC, m-c-hill commented on src/main/java/server/user/Registration.java
> +	public boolean checkLoginExists(String login){
I'll move this to dbUtils

2021-08-01 21:00 UTC, bnaylor1989 approved these changes

2021-08-01 21:07 UTC, merged