Feature/remove account from user
bnaylor1989/NewBank pull request #19
Opened 2021-08-04 16:58 UTC by Ecenursahin

This is the account removal from the user feature.  
Now when a user removes an account it sends an SMS too.
I also tried to connect to the SQL code but it might need a correction.
In this branch I also solved the exit/Exit/EXIT bug.

2021-08-04 19:37 UTC, m-c-hill commented on src/main/java/server/InputProcessor.java
> +                if (account.equals("Exit")||account.equals("EXIT")||account.equals("exit") ) {
Thanks for fixing the Exit bug! This could be simplified by using the equalIgnoreCase method, so could be be shortened to if(accountNumber.equalsIgnoreCase("Exit").

https://www.w3schools.com/java/ref_string_equalsignorecase.asp

2021-08-04 19:41 UTC, m-c-hill commented on src/main/java/server/NewBank.java
> +
Super clean code, well done!

2021-08-04 19:42 UTC, m-c-hill commented on src/main/java/server/NewBank.java
> +						}
Great bit of logic here. Makes sense that an account would not be able to be closed until the remaining balance has been withdrawn.

2021-08-04 19:51 UTC, m-c-hill commented on src/main/java/server/Customer.java
>  	}
Once the account has been removed, we'll also want to remove it from the database. The next step would be to create a static method in DbUtils that can run a delete statement in our database. 

This method should accept the account number of the account we want to remove and run a statement along the lines of:

"DELETE FROM account WHERE account_number=<account_number_we_pass_to_method>"

We would then call this new method in the removeAccount method above (ie. DbUtils.removeAccount(account.getAccountNumber()).

Here's a guide on the SQL side of things: https://www.w3schools.com/sql/sql_delete.asp

2021-08-04 19:52 UTC, m-c-hill commented on src/main/sql/schema/new_bank_schema.sql
> +
This is not quite right and should be removed

2021-08-04 19:55 UTC, m-c-hill requested changes
Some really excellent work here! The code is really well strucutured and logic is clearly laid out. 

I've left some comments regarding the database/SQL stuff - let me know if you need any help with this.

2021-08-04 22:26 UTC, Ecenursahin commented on src/main/java/server/InputProcessor.java
> +                if (account.equals("Exit")||account.equals("EXIT")||account.equals("exit") ) {
That's great to know, I am fixing it that way! Thank you!

2021-08-04 22:26 UTC, Ecenursahin commented on src/main/java/server/NewBank.java
> +						}
Thank you Matt!

2021-08-04 22:26 UTC, Ecenursahin commented on src/main/java/server/NewBank.java
> +
Thank you!

2021-08-07 12:22 UTC, m-c-hill requested changes
Just need to resolve the SQL statement issue as discussed offline

2021-08-07 12:22 UTC, m-c-hill commented on src/main/java/server/DbUtils.java
> +    }
One small improvement here. The removeAccount method is almost correct - you just need to change the accountNum to a question mark. You'll then need to insert the accountNum variable into the statement.

Here's a helpful video that explains it: https://www.youtube.com/watch?v=gU3DLOsw0Eg

So you supply a String query with the variable that you want to insert as "?". Then you create a prepared statement object and then you need to insert the variables into that statement using the "set" methods.

For example,
`preparedStatement.setInt(1, accountNum);`

The 1 refers to the position of the question mark in your statement (so in this case it's the first question mark)

2021-08-07 12:23 UTC, Ecenursahin commented on src/main/java/server/DbUtils.java
> +    }
Thank you so much Matt! Now it is much clearer, I was a little confused about the "?" in the statements.

2021-08-07 21:38 UTC, Ecenursahin commented
This pull request is replaced by the feature/remove _account_updated branch due to many refactoring conflicts.

2021-08-07 21:38 UTC, closed without merging