2fa sunday
bnaylor1989/NewBank pull request #23
Opened 2021-08-07 07:15 UTC by kezuk23

The pull request from the work from last sprint. It's been refactored into its own class and hopefully the implementation is correct. Sorry if it's a little bit messy!

2021-08-07 11:22 UTC, m-c-hill commented on src/main/java/server/InputProcessor.java
> +                    continue;
This continue can be removed as the code will continue once it reaches this point regardless

2021-08-07 11:22 UTC, m-c-hill commented on src/main/java/server/TwoFactorAuth.java
> +        return expectedCode;
Good use of random number generation!

2021-08-07 11:28 UTC, m-c-hill commented on src/main/java/server/TwoFactorAuth.java
> +        String inputCode = InputProcessor.takeCodeInput("four digit code", in, out);
You'll need to initialise the BufferedReader and Printwriter objects as you're currently passing in uninitialised objects.

2021-08-07 11:29 UTC, m-c-hill commented on src/main/java/server/InputProcessor.java
> +        "four digit codes", "^[0-9]{4}$"
Good additions to the regex list!

2021-08-07 11:31 UTC, m-c-hill commented on src/main/java/server/TwoFactorAuth.java
> +}
Very clean and easy to read!

2021-08-07 11:33 UTC, m-c-hill requested changes
2FA logic is very well thought out and is a great feature to add to the NewBank app, well done! Code is clearl and easy to read.

The one change that needs to be made for this to work is to initialise your BufferedReader and PrintWriter in the codeInput method.

2021-08-07 12:01 UTC, Ecenursahin reviewed
Simon, this is a very clean implementation and a great addition to our bank system. I agree with Matt's suggestion. Thank you for working on this element!

2021-08-07 13:00 UTC, kezuk23 commented on src/main/java/server/TwoFactorAuth.java
> +        String inputCode = InputProcessor.takeCodeInput("four digit code", in, out);
Added

2021-08-07 22:00 UTC, AllenNinous approved these changes
Nicely done Simon. It's also nice to see that this functionality is encapsulated in a class of its own. Great job.

2021-08-08 09:01 UTC, kezuk23 reviewed
Thanks for that Ben, I can't approve this so we just need somebody else to approve before merging! @Ecenursahin @AllenNinous are you able to approve and merge?

2021-08-08 11:00 UTC, m-c-hill approved these changes

2021-08-08 11:01 UTC, merged