Added make deposit feature and create account features
bnaylor1989/NewBank pull request #5
Opened 2021-07-12 00:14 UTC by Ecenursahin

Also added a test case where there is no accounts for a user

2021-07-12 19:50 UTC, bnaylor1989 requested changes

2021-07-12 19:50 UTC, bnaylor1989 commented on src/main/java/server/InputProcessor.java
> +                // If the name is not used before then accept it
It would be nice to give the user the option to break out of this loop without having to create a new account. 
For instance, they may want to go back and checko what accounts they currently have.
Maybe they could type 'exit' and be taken back to the main menu?

2021-07-12 19:50 UTC, bnaylor1989 commented on src/main/java/server/InputProcessor.java
> +        while (true) {
As with the comment about creating an account, I think the user should have the option to exit out of this if they want, without making a deposit.

2021-07-12 19:50 UTC, bnaylor1989 commented on src/main/java/server/NewBank.java
> +			return (customers.get(customer.getKey())).accountsToString();
Could you make a slight change to how this method displays multiple accounts. At the moment they are all printed on one line, as shown in the screenshot. All you will need to do I think is to add a newline (\n) after each iteration performed in the accountsToString method.

<img width="288" alt="Screenshot 2021-07-12 at 20 43 12" src="https://user-images.githubusercontent.com/36206067/125346576-d6c4a600-e351-11eb-9e70-56e6553a43a4.png">

2021-07-12 19:50 UTC, bnaylor1989 commented on src/main/java/server/NewBank.java
> +
Please remove extra blank line

2021-07-12 23:40 UTC, Ecenursahin commented on src/main/java/server/InputProcessor.java
> +                // If the name is not used before then accept it
Thank you, for the review Ben. I made the changes to include exit to main menu option for all make withdraw, deposit and create account operations.

2021-07-12 23:40 UTC, Ecenursahin commented on src/main/java/server/InputProcessor.java
> +        while (true) {
Thank you, for the review Ben. I made the changes to include exit to main menu option for all make withdraw, deposit and create account operations.

2021-07-12 23:41 UTC, Ecenursahin commented on src/main/java/server/NewBank.java
> +			return (customers.get(customer.getKey())).accountsToString();
Thank you, for the review Ben. I made the change in customer class to the accountsToString method.

2021-07-12 23:42 UTC, Ecenursahin commented on src/main/java/server/NewBank.java
> +
Thank you, for the review Ben. I erased the extra line.

2021-07-13 07:53 UTC, bnaylor1989 approved these changes
Looks good. Thanks for making those changes I asked for. Approved!

2021-07-13 11:14 UTC, merged