Refactoring: Object Relational Mapping
bnaylor1989/NewBank pull request #8
Opened 2021-07-22 19:55 UTC by m-c-hill

2021-07-23 14:15 UTC, bnaylor1989 requested changes
Some really great work here Matt! Just a few minor comments.

2021-07-23 14:15 UTC, bnaylor1989 commented on src/main/sql/queries/example_query.sql
> +LEFT JOIN user u ON u.user_id = a.user_id
I had forgotten how to use JOIN but this makes a lot of sense now I can see how you are  building your SQL queries.

2021-07-23 14:15 UTC, bnaylor1989 commented on src/main/sql/schema/populate_dummy_data.sql
> +ALTER TABLE newbank.account AUTO_INCREMENT = 1;
I see you have used the AUTO_INCREMENT feature. I mentioned it in a previous comment. Does this solve your issue around generating unique ID's now then? Does this mean that the account_number of the first record will be "1"? If so is there a way to make it an 8 digit number, i.e. 00000001.

What happens if you have:
ALTER TABLE newbank.account AUTO_INCREMENT = 00000001;
instead?

2021-07-23 21:13 UTC, m-c-hill commented on src/main/java/server/Address.java
> +				   String addressLine1,
Fixed

2021-07-23 21:13 UTC, m-c-hill commented on src/main/java/server/Account.java
> +	private void updateBalance(double newBalance){
Fixed

2021-07-23 21:13 UTC, m-c-hill commented on src/main/java/server/AdminRole.java
> +public class AdminRole {
I'll try and simplify this on Monday if that's okay

2021-07-23 21:15 UTC, m-c-hill commented on src/main/java/server/Registration.java
> +		String nationalInsuranceNumber = InputProcessor.takeValidInput("numbers", in, out);
I think we need to update the InputProcessor class to take in both letters and numbers.

I'll add a TODO and add it to the backlog as a matter of urgency.

2021-07-23 21:28 UTC, m-c-hill commented on src/main/java/server/Account.java
> +	public Account(String accountNumber, double openingBalance) {
Yep good point - I look into APIs and replace this once I've found something suitable.

2021-07-24 01:37 UTC, kezuk23 commented on src/main/java/server/Account.java
> +		this.accountNumber = accountNumber; // TODO: find a way to generate unique account IDs to replace user input
Great idea. Using the auto increment we can also set it to be (for example) an 8 digit number like in regular banks by using:

"To let the AUTO_INCREMENT sequence start with another value, use the following SQL statement:

ALTER TABLE Persons AUTO_INCREMENT=10000000;"

This can be added to the next sprint backlog.

2021-07-24 01:52 UTC, kezuk23 commented on src/main/java/server/Address.java
> +		}
I wonder if we'll encounter any issues with addresses that don't have a number associated with them either? Some UK addresses might just be the name of the house "Manor House Farm, Shortland Street, W Yorks" for example. Should we add an additional else statement here for that?

2021-07-24 02:43 UTC, kezuk23 commented on src/main/java/server/Balance.java
> +		// Returns true if this balance is to be used as the primary balance for transactions / transfers
Will this cause any issues when transferring different balances? Would a user have to change their primary balance before sending money from their secondary balance/crypto wallet?

2021-07-24 02:59 UTC, kezuk23 commented on src/main/java/server/Currency.java
> +		// Method to get the current exchange rate from the database
Agreed. From a quick Google search it looks like there are plenty of free ones, some of which provide cryptocurrency rates alongside general forex. Handy! I've added a comment to the card on Trello.

2021-07-24 09:04 UTC, bnaylor1989 commented on src/main/java/server/Address.java
> +		}
Good shout.

2021-07-24 09:06 UTC, bnaylor1989 approved these changes

2021-07-24 09:32 UTC, merged